#! /bin/sh
#
# This wraps compute_boot so that we can pass secrets to it quietly.

set -eu

basedir=/opt/confidentsec
targetdir=/var/confidentsec/etc
# shellcheck source=/dev/null
. ${basedir}/etc/system.conf
mkdir -p /run/environment.d
touch /run/environment.d/system.conf
# shellcheck source=/dev/null
. /run/environment.d/system.conf

exec "${basedir}/bin/compute_boot" -config "${targetdir}/compute_boot.yaml"
