#! /bin/sh
#
# This wraps router_com so that we can pass secrets to it quietly.

set -eu

basedir=/opt/confidentsec
targetdir=/var/confidentsec/etc
# shellcheck source=/dev/null
. ${basedir}/etc/system.conf
mkdir -p /run/environment.d
touch /run/environment.d/system.conf
# shellcheck source=/dev/null
. /run/environment.d/system.conf

exec "${basedir}/bin/router_com" -config "${targetdir}/router_com.yaml"
